### ISSUE TITLE
Make a 1.0.0 release

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#21]
After #18, #19 and #20 are merged, I think it could be time for a new major release. (#2 probably will take some more time to refine, and is a clearly separate feature.)

@CorreyL and @Mystic-Mirage, what do you think, is darker mature enough for a 1.0 release, or should we go with one more pre-1.0 version number?

- [x] bump version number (#29)
- [x] update change log (#29)
- [ ] implement #27 (document `--diff` for VS Code – @Carreau)
- [ ] review #27 
- [ ] merge #27
- [x] review #29 (1.0.0 release)
- [ ] merge #29 (correct date in `CHANGES.rst` if later than 2020-07-15)
- [ ] tag
- [ ] upload to PyPI
- [ ] bump `master` version number to 1.0.1.dev

**Comment by Mystic-Mirage** [comment]
Vote for 1.0

No time to be shy ;)

**Comment by CorreyL** [comment]
> (#2 probably will take some more time to refine, and is a clearly separate feature.)

Agreed on this point, and 1.0 sounds good to me!
